export const genreMapping: { [key: number]: string } = {
    28: "Ação",
    12: "Aventura",
    16: "Animação",
    35: "Comédia",
    80: "Crime",
    99: "Documentário",
    18: "Drama",
    10751: "Família",
    14: "Fantasia",
    36: "História",
    27: "Terror",
    10402: "Música",
    9648: "Mistério",
    10749: "Romance",
    878: "Ficção científica",
    10770: "Cinema TV",
    53: "Thriller",
    10752: "Guerra",
    37: "Faroeste",
    10759: "Ação & Aventura",
    10762: "Kids",
    10763: "News",
    10764: "Reality Show",
    10765: "Sci-Fi & Fantasia",
    10766: "Novelas",
    10767: "Talk Show",
    10768: "Guerra & Política",
    10769: "Estrangeiro",
    2: "Biografia",
    6: "Esporte",
    7: "Curta-metragem",
    8: "Experiência interativa",
    9: "Filme Noir",
    10: "Drama adolescente",
    11: "Fantasia sombria",
    13: "Tokusatsu",
    15: "Psicológico",
    17: "Filmagem direta",
    19: "Musical",
    20: "Comédia negra",
    21: "Docuficção",
    22: "Filosofia",
    23: "Natureza",
    24: "Patrimônio cultural",
    25: "Experimentos",
    26: "Paródia",
    29: "Mitologia",
    30: "Culto",
    31: "Satira política",
    32: "Gênero épico",
    33: "Fantasia urbana",
    34: "Espionagem",
    38: "Ficção futurista",
    39: "Distopia",
    40: "Sobrenatural",
    41: "Animação japonesa",
    42: "Mistério criminal",
    43: "Mistério sobrenatural",
    44: "Ciberpunk",
    45: "Steampunk",
    46: "Zumbi",
    47: "Kaiju",
    48: "Super-heróis",
    49: "Comédia romântica",
    50: "Aventura distópica",
    51: "Mistério de assassinato",
    52: "E-sportes",
    54: "Retro-futuro",
    55: "Mitologia grega",
    56: "Robôs",
    57: "Multiverso",
    58: "Assassinato",
    59: "Lendas urbanas",
    60: "Antologia",
    61: "Ninja",
    62: "Aliens",
    63: "Viagem no tempo",
    64: "Mistério policial",
    65: "Ficção histórica",
    66: "RPG",
    67: "Thriller psicológico",
    68: "Mistério médico",
    69: "Horror",
    70: "Horror Lovecraftiano",
    71: "Romance adolescente",
    72: "Religioso",
    73: "Culinária",
    74: "Moda",
    75: "Artes marciais",
    76: "Naval",
    77: "Escolas e Faculdade",
    78: "Tecnologia",
    79: "Medieval",
    81: "Corridas",
    82: "Policial",
    83: "Investigação forense",
    84: "Crime psicológico",
    85: "Fantasia medieval",
    86: "Mistério histórico",
    87: "Esporte de aventura",
    88: "Sobrevivência",
    89: "Conspiração",
    90: "Guerra futura",
    91: "História alternativa",
    92: "Mistério sobrenatural",
    93: "Ficção distópica",
    94: "Drama médico",
    95: "Família sobrenatural",
    96: "Comédia de horror",
    97: "Filmes de culto",
    98: "True Crime",
    100: "Histórias de fantasmas",
  };