# Use a imagem oficial do Python como base
FROM python:3.11-slim

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar os arquivos de requisitos (requirements.txt) para o contêiner
COPY requirements.txt /app/

# Instalar as dependências do projeto
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copiar o restante do código do projeto para o contêiner
COPY . /app/

# Expor a porta onde o Django será executado (padrão: 8000)
EXPOSE 8000

# Definir o comando padrão para rodar o servidor de desenvolvimento do Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
