# Usando a imagem oficial do Python
FROM python:3.11-slim

# Define o diretório onde o aplicativo Django será executado
WORKDIR /app

# Instala dependências do sistema, incluindo libpq-dev
RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

# Copio o arquivo requirements.txt para o contêiner Docker
COPY requirements.txt /app/

# Instalo as dependências do projeto
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copio o restante do código do projeto para o contêiner
COPY . /app/

# Expor a porta onde o Django será executado (padrão: 8000)
EXPOSE 8000

# Definir o comando padrão para rodar o servidor de desenvolvimento do Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
