# host replication ${DB_USER} 172.18.0.0/16 trust
#host replication postgres 172.18.0.0/16 trust
# host    replication    all    172.18.0.5/32    trust
# Permitir replicação do contêiner réplica
host    replication     replicator      172.18.0.3/32       md5
