# Generated by Django 5.1.1 on 2024-11-28 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_overview_movies',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_overview_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment_overview_series',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_overview_series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overview_movie',
            name='id_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie'),
        ),
        migrations.AddField(
            model_name='overview_movie',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment_overview_movies',
            name='id_overview_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.overview_movie'),
        ),
        migrations.AddField(
            model_name='overview_serie',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview_series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment_overview_series',
            name='id_overview_serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.overview_serie'),
        ),
        migrations.AddField(
            model_name='overview_serie',
            name='id_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.series'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movies',
            field=models.ManyToManyField(blank=True, to='app.movie'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='series',
            field=models.ManyToManyField(blank=True, to='app.series'),
        ),
    ]
